/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 Airplane.gltf --transform 
Files: Airplane.gltf [21.91MB] > Airplane-transformed.glb [1.15MB] (95%)
Author: Tim Samedov (https://sketchfab.com/citizensnip)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yakovlev-yak-28p-d8fb2ad3d871437392453568c0c8bfe8
Title: Yakovlev Yak-28P
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Airplane-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Yak28p_BODY1_0.geometry} material={materials.BODY1} position={[0, 87.138, 11.42]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Yak28p_BODY2_0.geometry} material={materials.BODY2} position={[0, 87.138, 11.42]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Yak28p_BODY2_0_1.geometry} material={materials.BODY2_0} position={[0, 87.138, 11.42]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Yak28p_K27_0.geometry} material={materials.material} position={[0, 87.138, 11.42]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Yak28p_Material_#381_0'].geometry} material={materials.Material_381} position={[0, 87.138, 11.42]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Yak28p_Panel_0.geometry} material={materials.Panel} position={[0, 87.138, 11.42]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Yak28p_Gondola_0.geometry} material={materials.Gondola} position={[0, 87.138, 11.42]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.OBJ0026_003lpaa_0.geometry} material={materials['003l.paa']} position={[0, 87.138, 11.42]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Airplane-transformed.glb')
